name: AppSec IL 2023

on: push 

jobs:
  appsecil:
    runs-on: ubuntu-latest
    name: Hello World
    permissions: 
      issues: write
    steps:
      - run: id
      - run : echo "Hallo World AppSec IL 2023"
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://juice-shop.herokuapp.com'
  secondjob:
    runs-on: ubuntu-latest
    name: Second job
    steps:
        - run: id
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    

